### ISSUE TITLE
Change Confessional namings to Playerchat namings

### ISSUE THREAD

**Issue by Lunethia** [JacksonVirgo/Mafia-Engine-Discord-Bot#2]
I will do it myself if you don't do it and pullrequest it.
To be fair, in code stuff can stay as is if you prefer working with it like that, but displayed messages being changed to "player chat" would be preferred.

Such as "Welcome to your player chat, all interactions between you and the host will happen here" (wording may differ)

**Comment by JacksonVirgo** [comment]
This is a minor change, feel free to do so yourself and send through a pull-request. Otherwise, I can get to it once the other more important matters are dealt with.

**Comment by LunexSan** [comment]
I will do it myself then, here's hoping I don't fuck anything up

**Comment by JacksonVirgo** [comment]
I'll always review the pull request and let you know if it's a breaking change etc

**Comment by LunexSan** [comment]
#6 

Please check if this breaks anything, I have no idea what I'm doing. Hope I changed all of them.
