### ISSUE TITLE
Add auto timestamps

### ISSUE THREAD

**Issue by Lunethia** [JacksonVirgo/Mafia-Engine-Discord-Bot#5]
Add the ability to easily create discord timestamps using the bot (no longer needed to go to hammertime or make it yourself entirely even)

**Comment by JacksonVirgo** [comment]
Would a system similar to [Friend Time](https://novakevin.gitbook.io/friend-time) be a decent starting point?

**Comment by JacksonVirgo** [comment]
Closing as an external solution has been found, can reopen if that solution ever becomes a problem.
